### ISSUE TITLE
How to use this data for ASR?

### ISSUE THREAD

**Issue by ZhangShiyue** [CherokeeLanguage/cherokee-audio-data#1]
Hi Michael,

Thanks for this awesome resource! 

I'm trying to use this resource to train a speech recognition model. But I'm not sure which aligned text file I should use. Should I use the "data-chr.txt" file under each directory for the audio+text alignments?

Meanwhile, I'm wondering how you get "Jiɂő:li" this kind of representation of Cherokee text? It is not the transliteration I can get from https://www.cherokeedictionary.net/transliteration. Did you use some other tool? 
And if I want to convert it back to Cherokee Syllabary, is there an easy way to do that?

Thanks,
Shiyue

**Comment by ZhangShiyue** [comment]
Siyo Michael,

Thanks for your kind and comprehensive reply! Now I can understand it much better. Thank you!

Thanks again for this awesome resource! I can take advantage of your data to train an ASR->MC model. 

But I'm also hoping to train an ASR->Syllabary model. Because you have to drop some audios because of this no-available-pronunciation issue. So more data is available to train an ASR->Syllabary model. 

Do you have any aligned audio+syllabary data by any chance? I know walc has the transliteration of each audio and I can convert the transliterations to syllabary by Cherokee-English dictionary. But it may take a while to process. So, I would be very grateful if you have some audio+syllabary data that I can directly take advantage of.

I do have a telegram but have never used it. But feel free to contact me there if you prefer (9194485607).  Also, you can contact me via email (shiyue@cs.unc.edu). FIY, I'm a phd student at UNC working with Prof. Ben Frey on applying NLP for Cherokee revitalization. 

Thanks!
Shiyue

**Comment by michael-conrad** [comment]
email sent.
